### ISSUE TITLE
Track1: stETH withdrawal device

### ISSUE THREAD

**Issue by soundyogi** [lidont/lidont#15]
stETH in  (reward) -> timelock (reward) / withdraw -> ETH out

**Comment by xrchz** [comment]
Is this device also the reward token contract? and immutable?

**Comment by unforkableco** [comment]
we want to reward input if stETH and amount of time locked (and do we need a third pool for future stuff)

if the next contract can access the "shares" then I think yes?
Bur maybe its a better design to have a seperate reward contract

**Comment by soundyogi** [comment]
I "think" so. 
We want to reward stETH swappers and tockens locked until they are converted.
(we may want to have a third pool of tokens for incentive)

If it doesnt make sense otherwise to have a seperate token contract...

**Comment by xrchz** [comment]
Current plan, for lidont token contract:
- Immediate mint of LIDONT (reward) when stETH is deposited, assigned to depositor, proportional to the amount of stETH deposited.
- Withdrawn ETH can be assigned to an output pipe (another contract or arbitrary address? allowlist?) by the depositor.
- When the ETH goes to the output pipe (which can only happen when enough ETH is available), so does the LIDONT. Before then, both are locked pending.

**Comment by xrchz** [comment]
Implemented as of d3f01856fdb18dfe4aaed7f7fab40819f6928dbe
